package:
  name: "logger"
  version: "1.0.2"

source:
  git_url: https://github.com/MicheleTirico/logger

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python

about:
  home: https://github.com/MicheleTirico/logger
  summary: "logger"

extra:
  recipe-maintainers:
    - mtirico